#!/usr/bin/env bash

export PATH=$(dirname dot-merlin-reader):$PATH

touch .merlin && ocamlmerlin "$@" \
    | jq 'del(.timing)' \
    | jq 'del(.query_num)' \
    | sed -e 's:"[^"]*lib/ocaml:"lib/ocaml:g' \
    | sed -e 's:\\n:\
:g'
