name: Fuzzy CI

on:
  # push:
  #   branches: [ fuzzy-ci-artefacts-approach ]
  pull_request:
    branches: [ fuzzy-ci-artefacts-approach ]
    types: [ opened, synchronize, reopened, unlabeled, labeled ]

env:
  LABEL_NAME: fuzzy-diff-looks-good
  full_data: full_responses.json
  distilled_data: distilled_data.json
  full_diff: full_responses.diff
  distilled_diff: distilled_data.diff
  GITHUB_API_ISSUES: ${{ github.event.issues_url }}
  ARTIFACTS_DOWNLOAD: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}

jobs:
  # download_curl_api_url:
  #   runs-on: ubuntu-latest
  #   permissions: write-all
  #   # Both with and without permissions, I get a 401
  #   steps:
  #     - name: Run curl
  #       run: |
  #        curl -LOs -H "Authorization: Bearer ${{ secrets.FUZZY_CI_TOKEN }}" https://api.github.com/repos/pitag-ha/merlin/actions/artifacts/1043780208/zip -D headers.txt

  #     - name: Print return headers
  #       run: cat headers.txt

  #     - name: Ls
  #       run: lspi_url:
  #   runs-on: ubuntu-latest
  #   permissions: write-all
  #   # Both with and without permissions, I get a 401
  #   steps:
  #     - name: Run curl
  #       run: |
  #        curl -LOs -H "Authorization: Bearer ${{ secrets.FUZZY_CI_TOKEN }}" https://api.github.com/repos/pitag-ha/merlin/actions/artifacts/1043780208/zip -D headers.txt

  #     - name: Print return headers
  #       run: cat headers.txt

  #     - name: Ls
  #       run: ls

  #     - name: Try to unzip
  #       run: unzip zip || cat zip

  #     - name: ls
  #       run: ls

  #     - name: Try to unzip
  #       run: unzip zip || cat zip

  #     - name: ls
  #       run: ls

  artifact_names:
    runs-on: ubuntu-22.04
    name: Create persistant artifact names
    outputs:
      base_branch_dir: ${{ steps.base_branch.outputs.name}}
      merge_branch_dir: ${{ steps.merge_branch.outputs.name }}
      diff_dir: ${{ steps.diff.outputs.name }}
    env:
      base_branch_sha: ${{ github.event.pull_request.base.sha }}
      merge_branch_sha: ${{ github.sha }}
      source_branch_sha: ${{ github.event.pull_request.head.sha }}
      pr_num: ${{ github.event.pull_request.number }}
    steps:
      - name: Create name for base branch data
        id: base_branch
        run: echo "name=base-branch-$base_branch_sha-pr$pr_num" | tee -a "$GITHUB_OUTPUT"

      - name: Create name for merge branch data
        id: merge_branch
        run: echo "name=data-merge-branch-$base_branch_sha-$source_branch_sha-pr$pr_num" | tee -a "$GITHUB_OUTPUT"

      - name: Create name for diff
        id: diff
        run: echo "name=diff-$base_branch_sha...merge$source_branch_sha-pr$pr_num" | tee -a "$GITHUB_OUTPUT"

  approve:
    name: Approve diff
    needs: artifact_names
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'fuzzy-diff-looks-good'
    runs-on: ubuntu-22.04
    # FIXME: Which permission is necessary? 
    permissions: write-all
    env:
      gh_api_artifacts_url: ${{ github.event.pull_request.base.repo.url }}/actions/artifacts
      diff: ${{ needs.artifact_names.outputs.diff_dir }}
    steps:
      - name: Retreive diff artifact meta-data
        id: diff_metadata
        run: |
          all_artifacts=$(curl -sSL  $gh_api_artifacts_url)
          diff_artifact=$(echo "$all_artifacts" | jq "first(.artifacts[] | select(.name == \"$diff\")  )")
          id=$(echo "$diff_artifact" | jq ".id")
          echo "id=$id" | tee -a $GITHUB_OUTPUT
          workflow_run=$(echo "$diff_artifact" | jq ".workflow_run | .id")
          echo "workflow_run=$workflow_run" | tee -a $GITHUB_OUTPUT

      - name: Check if diff exists
        env:
          id: ${{ steps.diff_metadata.outputs.id }}
        run: |
          # FIXME (?)
          if [ -z $id ]; then
            printf "You seem to have tried to approve a diff that doesn't exist yet.\nWait for the diff to have been generated and then try again."
            # TODO: Remove the label
            exit 1
          else
            echo "Category data diff exists"
          fi

      - name: Download diff
        env:
          id: ${{ steps.diff_metadata.outputs.id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         # Doing this manually, since actions/download-artifact only works on the same workflow run on which the artifact was uploaded
         curl -sSLO -H "Authorization: Bearer $GITHUB_TOKEN" "$gh_api_artifacts_url/$id/zip" -D headers.txt

      - name: Try to unzip downloaded diff
        run: |
          unzip zip || (echo "Download of diff artifact failed" && cat headers.txt && cat zip && exit 1)

      - name: Compute full responses diff hash
        id: diff_hash
        run: |
          hash=$(sha256sum "$full_diff" | awk '{print $1}')
          echo "hash=$hash" | tee -a $GITHUB_OUTPUT

      - name: Write HTTP body to file
        env:
          repo_url: ${{ github.event.repository.html_url }}
          cat_workflow_run: ${{ steps.diff_metadata.outputs.workflow_run }}
          cat_diff_id: ${{ steps.diff_metadata.outputs.id }}
          cat_hash: ${{ steps.diff_hash.outputs.hash }}

        run: |
          # TODO: refactor this msg to something like in file message
          msg=$( cat <<EOF
          This PR introduces a change in some Merlin query response(s), which has been captured by the fuzzy-test CI. The fuzzy-test diffs of the CI have been approved in its following state:
          - Distilled data:
              - Data can be downloaded from $repo_url/actions/runs/$cat_workflow_run
                - Artifact name with data on target branch (i.e. \`master\` at (...)): (...)
                - Artifact name with data on PR merge branch, i.e. merge result of source branch (at (...)) and target branch: (...)
                - Artifact name with diff between the two:
              - Diff 256-sha: $cat_hash
          - Full responses:
              - Data can be downloaded from $repo_url/actions/runs/$cat_workflow_run
                - Artifact name with data on target branch (i.e. \`master\` at (...)): (...)
                - Artifact name with data on PR merge branch, i.e. merge result of source branch (at (...)) and target branch: (...)
                - Artifact name with diff between the two:
              - Diff 256-sha: <full_reponses_hash>
          EOF
          )
          jq -n --arg msg "$msg" '{ body: $msg }' | tee -a body.json

      - name: Write comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -LsX POST -H "Authorization: Bearer $GITHUB_TOKEN" -d @body.json https://api.github.com/repos/pitag-ha/merlin/issues/6/comments
          echo $?

  data:
    name: Generate data
    needs: artifact_names
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened' || ( github.event.action == 'unlabeled' && github.event.label.name == 'fuzzy-diff-looks-good'  ) )
    # if: false
    outputs:
      base_branch_dir: ${{ env.base_branch_dir }}
      merge_branch_dir: ${{ env.merge_branch_dir }}
    env:
      base_branch_sha: ${{ github.event.pull_request.base.sha }}
      merge_branch_sha: ${{ github.sha }}
      base_branch_dir: ${{ needs.artifact_names.outputs.base_branch_dir }}
      merge_branch_dir: ${{ needs.artifact_names.outputs.merge_branch_dir }}
    strategy:
      matrix:
        commit: ["merge_branch", "base_branch"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checking out ${{ matrix.commit }}
      run: |
        sha=$${{ matrix.commit }}_sha
        # echo "sha=$sha" >> $GITHUB_ENV
        echo "Check out $sha"
        git checkout $sha


    # - name: Check if merge was fast-forwarded
    #   if: ${{ matrix.commit == 'merge-commit' }}
    #   run: |
    #     merge_sha=$${{ matrix.commit }}
    #     source=$(git rev-parse $merge_sha^2)
    #     git diff $merge_sha $source

    - name: Create artifact dir
      run: mkdir -p data

    - name: Create data
      run: |
        # echo "whatever ${{matrix.commit}}, run num: ${{ github.run_number }}" > "$distilled_data"
        # echo "whetever else ${{matrix.commit}}, run num: ${{ github.run_number }}" > "$full_data"
        echo "whatever ${{matrix.commit}}" > "$distilled_data"
        echo "whetever else ${{matrix.commit}}" > "$full_data"
      working-directory: data

    - name: Create name for matrix entry data
      run: echo "data_dir=$${{ matrix.commit }}_dir" >> $GITHUB_ENV

    - name: Upload data
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.data_dir }}
        path: data

  diff:
    name: Generate diff(s)
    runs-on: ubuntu-22.04
    outputs:
      diff_exits: ${{steps.full_responses_diff.outputs.diff_exists}}
    needs: [data, artifact_names]
    env:
      base: ${{ needs.artifact_names.outputs.base_branch_dir }}
      merge: ${{ needs.artifact_names.outputs.merge_branch_dir }}
      diff: ${{ needs.artifact_names.outputs.diff_dir }}
    steps:
      - name: Download base branch data
        env:
          data_dir: ${{ env.base }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.data_dir }}
          path: data-${{ env.data_dir }}

      - name: Download merge branch data
        env:
          data_dir: ${{ env.merge }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.data_dir }}
          path: data-${{ env.data_dir }}

      - name: Create diff dir
        run: mkdir -p data

      - name: Generate full responses diff
        id: full_responses_diff
        # TODO: Make this more readable. Also, it could be estracted to avoid the duplication the in next step.
        # To guarantee idempotence in diff generation, we're using `--labels` to avoids time stamps and sha's
        run: (diff -U 1 --label="base-branch-data" --label="merge-branch-data" "data-$base/$full_data" "data-$merge/$full_data" > "data/$full_diff" && echo "diff_exists=false" | tee -a "$GITHUB_OUTPUT" ) || echo "diff_exists=true" | tee -a "$GITHUB_OUTPUT"


      - name: Generate category data diff
        if: ${{ steps.full_responses_diff.outputs.diff_exists}}
        id: category_data_diff
        # To guarantee idempotence in diff generation, we're using `--labels` to avoids time stamps and sha's
        run: (diff -U 1 --label="base-branch-data" --label="merge-branch-data" "data-$base/$distilled_data" "data-$merge/$distilled_data" > "data/$distilled_diff" && echo "diff_exists=false" | tee -a "$GITHUB_OUTPUT" ) || echo "diff_exists=true" | tee -a "$GITHUB_OUTPUT"

      - name: Upload diff(s)
        if: ${{ steps.full_responses_diff.outputs.diff_exists}}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.diff }}
          path: data/

  output:
    name: Evaluate diff
    runs-on: ubuntu-22.04
    needs: [diff, artifact_names]
    permissions:
      pull-requests: write
    env:
      earlier_diff_was_approved: ${{ contains(github.event.pull_request.labels.*.name, 'fuzzy-diff-looks-good') }}
      current_diff_exists: ${{ needs.diff.outputs.diff_exits }}
      diff_dir: ${{ needs.artifact_names.outputs.diff_dir }}
    steps:
      - name: Download current diff(s)
        if: ${{ env.current_diff_exists == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.diff_dir }}

      - name: Get body of approval comment on PR
        if: ${{ env.earlier_diff_was_approved == 'true' }}
        id: approval_comment
        env:
          msg_start: "This PR introduces a change in some Merlin query response(s), which has been captured by the fuzzy-test CI."
          github_api_comments_url: ${{ github.event.pull_request.base.repo.url }}/issues/6/comments
        run: |
          # FIXME: Don't hardcode the url
          # FIXME: This will give a wrong result, if the PR had more than 100 comments before the last diff approval
          body=$(curl -s "https://api.github.com/repos/pitag-ha/merlin/issues/6/comments?per_page=100" | jq --arg msg_start "$msg_start" 'map(select(.body | startswith($msg_start))) | max_by(.'created_by') | .body' | tee -a)
          echo "body='$body'" | tee -a $GITHUB_OUTPUT

      - name: Retreive hash of approved diff
        if: ${{ env.earlier_diff_was_approved == 'true' }}
        id: approved_diff_info
        run: |
          hash=$(echo ${{ steps.approval_comment.outputs.body }} | jq -r | awk '/- Distilled data:/,/^- Full responses:/ {if(!/^- Full responses:/) print}' | grep 'Diff 256-sha' | awk '{print $NF}')
          echo "hash='$hash'" | tee -a $GITHUB_OUTPUT

      - name: Return
        env:
          github_api_labels_url: ${{ github.event.pull_request.base.repo.url }}/issues/${{ github.event.pull_request.number }}/labels
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if $earlier_diff_was_approved; then
            echo "Earlier diff was approved."
            current_diff_hash=$(sha256sum $full_diff | awk '{print $1}')
            if [ "$current_diff_hash" == ${{ steps.approved_diff_info.outputs.hash }} ]; then
              echo "This diff has been approved earlier. Everything ok."
              exit 0
            else
              echo "--------beginning of full reponses diff--------"
              cat "$full_diff"
              echo "--------end of full reponses diff--------"
              echo "--------beginning of distilled data diff--------"
              cat "$distilled_diff"
              echo "--------end of distilled data diff--------"
              echo "The diff has changed since it was approved. You can find the new diff(s) printed above or download them from ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }} . If the new diff looks good, please set the $LABEL_NAME label on the PR again. I'm removing the $LABEL_NAME label for now."
              status=$(curl -sL -w "%{http_code}" -o output.txt -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/pitag-ha/merlin/issues/6/labels/fuzzy-diff-looks-good)
              if [ "$status" -ne 200 ]; then
                echo "Something went wrong trying to remove the $LABEL_NAME label. Please, remove it manually if the diff doesn't look good to you."
              cat output.txt
              fi
              exit 2
            fi
          else
            if $current_diff_exists; then
              echo "--------beginning of full reponses diff--------"
              cat "$full_diff"
              echo "--------end of full reponses diff--------"
              echo "--------beginning of distilled data diff--------"
              cat "$distilled_diff"
              echo "--------end of distilled data diff--------"
              echo "Diff can also be downloaded from ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }} . If it looks good, please set the $LABEL_NAME label on the PR."
              exit 1
            else
              echo "No diff. All good."
              exit 0
            fi
          fi



    # - name: log PR target
    #   run: git log remotes/origin/${{ github.base_ref }} -n 3

    # - name: Find common ancestor
    #   run: |
    #     common_ancestor = $(git merge-base ${{ github.ref }} ${{ github.base_ref }})
    #     echo "Common ancestor: $common_ancestor"



#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install OCaml
#         uses: ocaml/setup-ocaml@v2
#         with:
#           # When updating the compiler here, also update the Irmin build on ... to the new compiler
#           ocaml-compiler: ocaml-base-compiler.4.14.1
#           dune-cache: true

#       - name: Install dependencies
#         run: opam install --deps-only .

# # TODO: rebase over master before installing merlin.

#       - name: Install merlin
#         run: |
#           opam exec -- dune subst
#           opam exec -- dune build
#           opam exec -- dune install

#       - name: Install merl-an
#         run: opam pin -y merl-an https://github.com/pitag-ha/merl-an.git

#       - name: Set up ssh env
#         uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.DEPLOY_KEY_FOR_FUZZY_CI }}

#       - name: Clone data repo
#         run: git clone git@github.com:pitag-ha/merlin-fuzzy-ci-data.git data

#       - name: Configure git user
#         run: |
#           git config user.email "actions@github.com>"
#           git config user.name "Merlin Fuzzy CI"
#         working-directory: data

#       - name: Checkout new branch
#         run: |
#           git fetch origin
#           git checkout origin/main
#           git checkout -b yuhuuu
#         working-directory: data

#       - name: Build test code base
#         run: |
#           eval $(opam env)
#           dune build @check
#         working-directory: data/test-code-base/irmin

#       - name: Create new data
#         run: |
#           eval $(opam env)
#           merl-an behavior --queries=type-enclosing,occurrences,locate,complete-prefix,errors --sample-size=30 --data=irmin_data --merlin=ocamlmerlin --project=test-code-base/irmin/src/irmin/
#           # merl-an behavior --queries=type-enclosing,occurrences,locate,complete-prefix,errors --sample-size=30 --data=irmin_pack_data --merlin=ocamlmerlin --project=irmin/src/irmin-pack --extensions=ml
#           # merl-an behavior --queries=type-enclosing,occurrences,locate,complete-prefix,errors --sample-size=30 --data=irmin_pack_test_data --merlin=ocamlmerlin --project=irmin/test/irmin-pack --extensions=ml
#         working-directory: data

#       - name: Commit new data
#         run: |
#           git add irmin_data
#           git commit -m "Updated data from PR ..."
#         working-directory: data

#       - name: Push new data
#         run: git push --set-upstream -f origin yuhuuu
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_FOR_FUZZY_CI }}
#         working-directory: data

#       - name: Diff new data with old data
#         run: |
#           if [[ -n $(git diff origin/main) ]]; then
#             echo "See diff on https://github.com/pitag-ha/merlin-fuzzy-ci-data/compare/main...yuhuuu"
#             exit 1
#           else
#             echo "All good: No diff on merl-an's sample set."
#           fi
#         working-directory: data
