name: Execute privileged instructions

env:
  GH_API_ACTIONS: https://api.github.com/repos/${{ github.repository }}/actions

on:
  workflow_run:
    workflows: ["Foo"]
    types:
      - completed

jobs:
  execute-instruction:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Print pull_request context
        run: |
          echo "${{ toJson(github.event.workflow_run) }}"
      - name: Print headers
        run: |
          cat headers.txt
      - name: all_artifacts
        run: |
          curl -sSL  "$GH_API_ACTIONS/runs/${{ github.event.workflow_run.id }}/artifacts"
      - name: Filtered artifacts
        run: |
          all_artifacts=$(curl -sSL  "$GH_API_ACTIONS/runs/${{ github.event.workflow_run.id }}/artifacts")
          echo $all_artifacts | jq '.artifacts[] | select(.workflow_run.id == ${{ github.event.workflow_run.id }} and .name == "forwarded_instructions")'
      - name: id
        run: |
          all_artifacts=$(curl -sSL  "$GH_API_ACTIONS/runs/${{ github.event.workflow_run.id }}/artifacts")
          forward_artifact=$(echo $all_artifacts | jq '.artifacts[] | select(.workflow_run.id == ${{ github.event.workflow_run.id }} and .name == "forwarded_instructions")')
          echo $forward_artifact | jq -r '.id'
      - name: endpoint
        run: |
          all_artifacts=$(curl -sSL  "$GH_API_ACTIONS/runs/${{ github.event.workflow_run.id }}/artifacts")
          forward_artifact=$(echo $all_artifacts | jq '.artifacts[] | select(.workflow_run.id == ${{ github.event.workflow_run.id }} and .name == "forwarded_instructions")')
          id=$(echo $forward_artifact | jq -r '.id')
          echo "$GH_API_ACTIONS/artifacts/$id/zip"
      - name: Download artifact
        run: |
          all_artifacts=$(curl -sSL  "$GH_API_ACTIONS/runs/${{ github.event.workflow_run.id }}/artifacts")
          forward_artifact=$(echo $all_artifacts | jq '.artifacts[] | select(.workflow_run.id == ${{ github.event.workflow_run.id }} and .name == "forwarded_instructions")')
          id=$(echo $forward_artifact | jq -r '.id')
          curl -sSLO -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$GH_API_ACTIONS/artifacts/$id/zip" -D headers.txt
      - name: Ls
        run: |
          ls -la
      - name: Unzip artifact
        run: |
          unzip -q zip -d forward || cat zip
      - name: Cat the artifact content
        run: |
          cat forward/instruction.json
