name: Foo

on:
  pull_request:
    branches: [ master ]

env:
  GH_API_LABELS: ${{ github.event.pull_request.issue_url }}/labels



  # DOWNLOAD_URL = $ACTIONS_RUNS_ENDPOINT/$approved_diffs_workflow_run
  # HASH=$approved_diffs_hash


jobs:
  share_instruction:
    runs-on: ubuntu-latest
    steps:
      - name: Forward instruction to delete the label to privileged workflow
        run: |
          mkdir -p ./forward
          jq -n \
            --arg instruction "delete_label" \
            --arg endpoint "$GH_API_LABELS" \
            '{instruction: $instruction, endpoint: $endpoint}' > ./forward/instruction.json
      - uses: actions/upload-artifact@v2
        with:
          name: forwarded_instructions
          path: forward/
